### ISSUE TITLE
survey of the Imagery Collection

### ISSUE THREAD

**Issue by sunghoonyang** [Streets-Data-Collaborative/groundwork-detection#12]
Amber and Karan,

Recapping our discussion from last week as following:

We will survey the [Imagery Collection](https://drive.google.com/open?id=1Sog0WTiPbTqZGdw25prTe2EDtQwfMsCG) that I have been producing. 

@karansaini282  Some questions:
* Can you get me and Amber up to speed to do this task together? Even before that, 
* Can we get upload access to the model you have trained so far? It would be ideal if we can, because we wouldn't want to train a model again, would we? 
* If you can think of a good workflow for this, please enlighten us. In fact, would you document the upload/train process in README.md under # Week 3 subtitle? Just few words and screenshots to describe upload/train process will suffice. Also, 
* how many images should we aim for? From the last week's discussion, the threshold of 30 images per category is the rule-of-thumb?

Other than that, let's share some concerns we each have to finish this proj asap. The first one that comes to my mind is that photos in Imagery Collection is sparse data (in a sense that the fraction of photos with legit traffic signs is tiny), so daily quota for requesting prediction to our trained model will throttle our process. This is fine, but the full scan of all images will take week(s). My suggestion is to 
1. train model with the fewest amount of images possible(~30 images?), and 
2. do scheduled batch job of prediction requests of our imagery, and 
3. accumulate the prediction results. 
I think this will help us focus on getting the preliminary results.  

Any other concerns you may have, please share in the thread, other than that, @karansaini282  please help me out by answering my questions, and any input that you think may help us train/predict photos easily.

**Comment by sunghoonyang** [comment]
First Iteration is complete; We will revamp this notebook for final reporting:
https://github.com/Streets-Data-Collaborative/groundwork-detection/blob/master/Signage/nb/neighborhood_metric_benchmark.ipynb

**Comment by vr00n** [comment]
Fantastic Stuff @sunghoonyang ! Please prepare a quick 5 min discussion for our next call this weekend!
