### ISSUE TITLE
Street View API - Targeting street signs specifically

### ISSUE THREAD

**Issue by karansaini282** [Streets-Data-Collaborative/groundwork-detection#5]
Using uniformly distributed coordinates over Manhattan with the Street View API result in very few images with street signs in them.

One trick which improved the percentage of images with street signs was using a NYC streets shape-file to traverse coordinates along NYC streets. Using only the sample with 25 - 50 percentile of street width resulted in about 15% images with street signs in a random sample of 160 images.

Further suggestions might help to improve the results.

**Comment by vr00n** [comment]
Thanks @karansaini282 . Let me clarify the task here. The task is to detect the type of street sign, not if an image has a street sign or not. 

So for this image, the model should try to identify all the highlighted signs.

![street](https://user-images.githubusercontent.com/4397663/50388762-f127cd00-06dc-11e9-9527-08286204de8a.jpg)

**Comment by vr00n** [comment]
@karansaini282 please close if resolved else any followups here?
