### ISSUE TITLE
Street View API - Handling downloads at scale

### ISSUE THREAD

**Issue by karansaini282** [Streets-Data-Collaborative/groundwork-detection#6]
The Street View script written by @karansaini282 crashes at large scale of downloads (~8000 downloads).

@sunghoonyang has suggested that a good way of scaling this script is to run it in smaller batches and keep moving the downloaded images to maybe a Google Drive.

**Comment by vr00n** [comment]
OK. Can you share the script on this issue thread please?
Please remember you are limited to 5,000 images in CustomVision free version.

**Comment by sunghoonyang** [comment]
@karansaini282 hi karan, I ran into HTTP 403 error after 6000 images... Is this the same error? It's not system crashing so I wouldn't think so. I'm writing images directly to mounted google drive fs, so I think im evading the problem u had. I will see if try/catch-ing 403 error can help me run full iteration of Manhattan road sweep..

**Comment by vr00n** [comment]
@karansaini282 @sunghoonyang - can this be closed? what was the resolution?

**Comment by sunghoonyang** [comment]
The new ETL code with direct write to mounted Google Drive file sys allowed ETL to finish without errors. I produced 75k images during 3 days without any failed execution
