### ISSUE TITLE
Import Images from Open Street Camera 

### ISSUE THREAD

**Issue by mv1742** [Streets-Data-Collaborative/groundwork-detection#9]
We couldn't import images from OSC. 
The scripts outputs a csv file only. 
We also tried to use the notebook here:
[osc-accel-parse.ipynb](https://github.com/Streets-Data-Collaborative/osc-tools/blob/master/osc-accel-parse.ipynb)

We wonder if you could tell us more about how to import the images.

**Comment by vr00n** [comment]
Hi @mv1742 - the csv file should contain partial links to the image in the following columns:

```
name
lth_name
th_name
```
these are locations to the images of varying sizes. 

For example - see here: https://github.com/Streets-Data-Collaborative/osc-tools/blob/master/osc-parse/1249727.csv

where name = `storage8/files/photo/2018/6/15/proc/1249727_45760_0.jpg`

you need to append `https://openstreetcam.org/` to this name.

So `https://openstreetcam.org/storage8/files/photo/2018/6/15/proc/1249727_45760_0.jpg` is the link to the image.

**Comment by vr00n** [comment]
@mv1742 if this works for you, please close or let me know if you are running into problems. thanks!

**Comment by muaz-urwa** [comment]
Yes this works perfectly fine. 
Also [this script](https://github.com/Streets-Data-Collaborative/OpenStreetCam-GeoParsing-Tool/blob/master/scripts/getAlltracks.py) from the geo-parsing project works and can be used to get tracks near a specified geolocation. 
So using this we have written a script that extracts all tracks in Manhattan and and then subsequently extracts images from these tracks. [script](https://github.com/Streets-Data-Collaborative/groundwork-detection/blob/master/Taxis/ETL_scripts/OpenStreetCamETL)
